name: Update, Sync and Deploy 🚀
  # uses: SamKirkland/FTP-Deploy-Action@4.3.3
on: push
jobs:
  deploy-job:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
      - run: echo "Deploying"
      # with:
      #   server: ${{ secrets.ftp_server }}
      #   username: ${{ secrets.ftp_username }}
      #   password: ${{ secrets.ftp_password }}
      #   server-dir: /public_html/admin-test-com/
      #   exclude: |
      #     public/**
      #     vendor/**
      #     crons/**
      #     storage/**
      #     .github
      #     .github/**
      #     .env
      #     composer.json
      #     composer.lock
      #     .htaccess